const chalk = require('chalk')
const validator = require('validator')
const getNotes = require('./notes.js')
const msg = getNotes()
console.log(msg)
console.log(validator.isEmail('shabnam@gmail.com'))
const greenmsg = chalk.green('success!')
console.log(greenmsg)
console.log(process.argv[2])
